name: shared matrix
on:
  push:
  workflow_dispatch:

jobs:
  define-matrix:
    runs-on: ubuntu-20.04

    outputs:
      colors: ${{ steps.colors.outputs.colors }}

    steps:
      - name: Define Colors
        id: colors
        run: |
          echo 'colors=["red", "green", "blue"]' >> "$GITHUB_OUTPUT"

  produce-artifacts:
    name: Produce
    runs-on: ubuntu-20.04
    needs: define-matrix
    strategy:
      matrix:
        color: ${{ fromJSON(needs.define-matrix.outputs.colors) }}

    steps:
      - name: Define Color
        env:
          color: ${{ matrix.color }}
        run: |
          echo "the current color is '$color'" > color.txt
      - name: ImageMagick Action
        uses: jruipinto/ImageMagick-action@v1
          # ImageMagick command to be executed
        with: 
          command: |
            magick -size 320x120 xc:lightblue \
             -draw "font Impact  font-size 72 \
                    fill ${{ matrix.color }}  stroke navy  stroke-width 2 \
                    translate 0,80  text 0,0 ' ${{ matrix.color }} '" \
            draw.png
      - name: Upload text - ${{ matrix.color }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.color }}
          path: color.txt
          retention-days: 5
      - name: Upload image - ${{ matrix.color }}
        uses: actions/upload-artifact@v4
        with:
          name: draw-${{ matrix.color }}
          path: draw.png
          retention-days: 5


  consume-artifacts:
    name: Consume
    runs-on: ubuntu-20.04
    needs:
    - define-matrix
    - produce-artifacts
    strategy:
      matrix:
        color: ${{ fromJSON(needs.define-matrix.outputs.colors) }}

    steps:
      - name: Retrieve text - ${{ matrix.color }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.color }}

      - name: Retrieve image - ${{ matrix.color }}
        uses: actions/download-artifact@v4
        with:
          name: draw-${{ matrix.color }}

      - name: Report Color
        run: |
          cat color.txt

      - name: Report image
        run: |
          stat draw.png
