name: Release Workflow
on:
  workflow_dispatch: {}
  workflow_call: {}
  push:
  pull_request: {}

jobs:
  core:
    name: Core Job
    uses: jadutter/test-gh-actions/.github/workflows/core.yml@develop
  matrix:
    name: Matrix Job
    uses: jadutter/test-gh-actions/.github/workflows/matrix.yml@develop
  release:
    name: Release Job
    needs: [core, matrix]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: '0'
      - name: Release Step
        run: echo 'release the latest version'
